//
// PostHighwayOrderRequestHighwayOrdersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostHighwayOrderRequestHighwayOrdersInner: Codable, Hashable {

    public var type: String
    public var category: String
    public var cost: Float
}

