//
// PostHighwayOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostHighwayOrderRequest: Codable, Hashable {

    public var highwayOrders: [PostHighwayOrderRequestHighwayOrdersInner]
}

